# This file was generated by GoReleaser. DO NOT EDIT.
cask "rscli@1.0.3" do
  name "rscli@1.0.3"
  desc "Reysys CLI"
  homepage "https://github.com/reysys-technology/rscli"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_darwin_amd64"
      sha256 "40737c90d8eeddd39e43f5813616498b6886b49bc3e98f0f14c064aae66aabdb"
      binary "rscli_darwin_amd64", target: "rscli"
    end
    on_arm do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_darwin_arm64"
      sha256 "205de4eb025cfcfa54347727c6cfb77915999af641fd797e54d258c547920663"
      binary "rscli_darwin_arm64", target: "rscli"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_linux_amd64"
      sha256 "0ae856ad0b10cf84d3ee68203b918148529d07b599b2f9a978dd8b3c5dac00d5"
      binary "rscli_linux_amd64", target: "rscli"
    end
    on_arm do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_linux_arm64"
      sha256 "2dae20bf9183f16029b0e63227aa823b2b516ecb6fa9af3f66978eaad449f2b6"
      binary "rscli_linux_arm64", target: "rscli"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
