# This file was generated by GoReleaser. DO NOT EDIT.
cask "rscli" do
  name "rscli"
  desc "Reysys CLI"
  homepage "https://github.com/reysys-technology/rscli"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_darwin_amd64"
      sha256 "b0b4e03d86b9f9b8e9efb58fc6abc83b0c720c80982ad225d5e1ccd744d5a378"
      binary "rscli_darwin_amd64", target: "rscli"
    end
    on_arm do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_darwin_arm64"
      sha256 "143e70bf64372637911b4a5c91c37cdc946eb144180a73e00e1918166260e4e8"
      binary "rscli_darwin_arm64", target: "rscli"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_linux_amd64"
      sha256 "e65b0f0d6681dac89c9bb772acd157e11753afea8937662383d125fa025d0793"
      binary "rscli_linux_amd64", target: "rscli"
    end
    on_arm do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_linux_arm64"
      sha256 "330532c4f675689e3175a38b7e4c663f04a099815915bb8e5152fc6bc2d38b5b"
      binary "rscli_linux_arm64", target: "rscli"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
