# This file was generated by GoReleaser. DO NOT EDIT.
cask "rscli@1.0.2" do
  name "rscli@1.0.2"
  desc "Reysys CLI"
  homepage "https://github.com/reysys-technology/rscli"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_darwin_amd64"
      sha256 "80b7639b5189cab5cf1ab104fcd7b7521d92b24b6f9ecc11ac182252485e9594"
      binary "rscli_darwin_amd64", target: "rscli"
    end
    on_arm do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_darwin_arm64"
      sha256 "f6448c791674d309e78853595d8a783dd78513610308b6edeabce96b20a76275"
      binary "rscli_darwin_arm64", target: "rscli"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_linux_amd64"
      sha256 "a3c361d46eecb0dc5e39d537e2ca4521864b5e0dcc64e9366124ec1e2a7c1764"
      binary "rscli_linux_amd64", target: "rscli"
    end
    on_arm do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_linux_arm64"
      sha256 "bac7c1138996984be51c0da99f1ed6a61ce579a9615e83feeb126cf6383f4cf9"
      binary "rscli_linux_arm64", target: "rscli"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
