# This file was generated by GoReleaser. DO NOT EDIT.
cask "rscli@1.0.2" do
  name "rscli@1.0.2"
  desc "Reysys CLI"
  homepage "https://github.com/reysys-technology/rscli"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_darwin_amd64"
      sha256 "e69c28735e7bcd603176f0e199e88e13092b2f6bffacecbfa3310634bef654c7"
      binary "rscli_darwin_amd64", target: "rscli"
    end
    on_arm do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_darwin_arm64"
      sha256 "c60e4a1a597841028a18d73f65efe5d153f6cd679cc871e1f926c7f9e5738677"
      binary "rscli_darwin_arm64", target: "rscli"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_linux_amd64"
      sha256 "856702e9474373f5b2416110f4a5296b7e83ae1b6f8faa2ee6e2fa8d81e28ba4"
      binary "rscli_linux_amd64", target: "rscli"
    end
    on_arm do
      url "https://github.com/reysys-technology/rscli/releases/download/v#{version}/rscli_linux_arm64"
      sha256 "7c9b085ff36c1f4f56bd0c414d6edb6d0fac1a64fc63beb35bf36d4118f7fd30"
      binary "rscli_linux_arm64", target: "rscli"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
